# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.23

# set version label
ARG BUILD_DATE
ARG VERSION
ARG SONARR_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thespad"

# set environment variables
ENV XDG_CONFIG_HOME="/config/xdg" \
  SONARR_CHANNEL="v4-stable" \
  SONARR_BRANCH="main" \
  COMPlus_EnableDiagnostics=0 \
  TMPDIR=/run/sonarr-temp

RUN \
  echo "**** install packages ****" && \
  apk add --no-cache \
    icu-libs \
    sqlite-libs \
    xmlstarlet && \
  mkdir -p /app/sonarr/bin && \
  echo -e "UpdateMethod=docker\nBranch=${SONARR_BRANCH}\nPackageVersion=${VERSION:-LocalBuild}\nPackageAuthor=[linuxserver.io](https://linuxserver.io)" > /app/sonarr/package_info && \
  printf "Linuxserver.io version: ${VERSION}\nBuild-date: ${BUILD_DATE}" > /build_version && \
  echo "**** cleanup ****" && \
  rm -rf \
    /tmp/*

COPY _artifacts/linux-musl-arm64/net6.0/Sonarr/ /app/sonarr/bin/

RUN rm -rf /app/sonarr/bin/Sonarr.Update

# add local files
COPY root/ /

# set executable bit
RUN chmod +x \
    /app/sonarr/bin/Sonarr \
    /app/sonarr/bin/ffprobe \
    /etc/s6-overlay/s6-rc.d/init-sonarr-config/run \
    /etc/s6-overlay/s6-rc.d/init-sonarr-config/up \
    /etc/s6-overlay/s6-rc.d/svc-sonarr/run \
    /etc/s6-overlay/s6-rc.d/svc-sonarr/data/check

# ports and volumes
EXPOSE 8989

VOLUME /config
